version: 2

updates:
  - package-ecosystem: composer
    directory: /app
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "fix"
      include: "scope"
    groups:
      symfony:
        patterns:
          - "symfony/*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "fix"
      include: "scope"
    groups:
      tests-navigateur:
        patterns:
          - "@axe-core/playwright"
          - "@playwright/*"
          - "playwright*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "fix"
      include: "scope"
    groups:
      actions-github:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /docker/php
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "fix"
      include: "scope"

  - package-ecosystem: docker
    directory: /docker/postgres
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "fix"
      include: "scope"

  - package-ecosystem: docker
    directory: /docker/liquibase
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "fix"
      include: "scope"
